default:
  image: gitlab.igalia.com:4567/teams/webkit/wkdev-sdk/ci-runner:latest
  tags:
    - amd64
  before_script:
    # The default branch is tagged with the 'latest' tag
    # All other branches are tagged with the escaped branch name (commit ref slug)
    - |
      echo "Environment:"
      echo "======================================================================"
      echo "CI_PIPELINE_SOURCE=\"$CI_PIPELINE_SOURCE\""
      echo "CI_REPOSITORY_URL=\"$CI_REPOSITORY_URL\""
      echo "CI_COMMIT_BRANCH=\"$CI_COMMIT_BRANCH\""
      echo "CI_COMMIT_SHA=\"$CI_COMMIT_SHA\""
      echo "CI_COMMIT_REF_SLUG=\"$CI_COMMIT_REF_SLUG\""
      echo "======================================================================"
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        export WKDEV_SDK_TAG="latest"
        echo "Running on default branch '$CI_DEFAULT_BRANCH': export WKDEV_SDK_TAG=$WKDEV_SDK_TAG"
      else
        export WKDEV_SDK_TAG="$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': export WKDEV_SDK_TAG=$WKDEV_SDK_TAG"
      fi
    - source ./register-sdk-on-host.sh

Build SDK:
  stage: build
  script:
    - wkdev-sdk-bakery --mode build --verbose
    - wkdev-sdk-bakery --mode export --verbose
  artifacts:
    paths:
      - wkdev-sdk.tar
    expire_in: 1 week

Test SDK:
  stage: test
  script:
    - podman load < wkdev-sdk.tar
    - wkdev-create --create-home --verbose --attach --no-pull
    - wkdev-enter --exec -- git clone --depth=1 https://github.com/WebKit/WebKit.git
    - wkdev-enter --exec -- ./WebKit/Tools/Scripts/build-webkit --wpe --release --generate-project-only
    - wkdev-enter --exec -- ./WebKit/Tools/Scripts/build-webkit --gtk --release --generate-project-only

Deploy SDK:
  stage: deploy
  script:
    - podman load < wkdev-sdk.tar
    - echo "$CI_REGISTRY_PASSWORD" | podman login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
    - wkdev-sdk-bakery --mode deploy --verbose
