#!/usr/bin/env python3
import sys
import os

# Configure jhbuild to be self-contained to /jhbuild
buildroot = '/jhbuild/build'
prefix = '/jhbuild/install'
tarballdir = '/jhbuild/downloads'
modulesets_dir = '/jhbuild'

if 'WKDEV_IN_IMAGE_BUILD' in os.environ:
    checkoutroot = '/jhbuild/checkout'
    shallow_clone = True
else:
    checkoutroot = os.path.expanduser('~/checkout')

# Whether to use a local copy of modulesets
use_local_modulesets = True
# Assume we have sysdeps installed
check_sysdeps = False
# List of modulesets to use
moduleset = [ '/jhbuild/webkit-sdk-deps.modules' ]
# A list of the modules to build.
modules = [ 'webkit-sdk-deps' ]
