#!/usr/bin/env python3
import sys
import os

# Configure jhbuild to be self-contained to /jhbuild
buildroot = '/jhbuild/build'
prefix = '/jhbuild/install'
tarballdir = '/jhbuild/downloads'
modulesets_dir = '/jhbuild'

if 'WKDEV_IN_IMAGE_BUILD' in os.environ:
    # In our image build we put these in a tmp directory not kept.
    checkoutroot = '/var/tmp/jhbuild/checkout'
    buildroot = '/var/tmp/jhbuild/build'
    shallow_clone = True
    # And we put this in a cached directory.
    tarballdir = '/var/cache/jhbuild/downloads'
    
else:
    checkoutroot = os.path.expanduser('~/checkout')

# Whether to use a local copy of modulesets
use_local_modulesets = True
# Assume we have sysdeps installed
check_sysdeps = False
# List of modulesets to use
moduleset = [ '/jhbuild/webkit-sdk-deps.modules' ]
# A list of the modules to build.
modules = [ 'webkit-sdk-deps' ]
