# Copyright 2024 Igalia S.L.
# SPDX-License: MIT

FROM ubuntu:24.04

LABEL maintainer="webkit-gtk@lists.webkit.org"
LABEL version="1.0"
LABEL org.opencontainers.image.title="WebKit SDK"
LABEL org.opencontainers.image.description="Provides a complete WebKit Gtk/WPE development environment based on Ubuntu 24.04"
LABEL org.opencontainers.image.source=https://github.com/Igalia/webkit-container-sdk

# Tweakable "make -j <x>" setting.
ARG NUMBER_OF_PARALLEL_BUILDS=4
ARG CONTAINER_LOCALE=en_US.UTF-8

# No need to modify these.
ARG APT_UPDATE="apt-get update"
ARG APT_BUILDDEP="apt-get --assume-yes build-dep"
ARG APT_UPGRADE="apt-get --assume-yes upgrade"
ARG APT_INSTALL="apt-get --assume-yes install --no-install-recommends"
ARG APT_AUTOREMOVE="apt-get --assume-yes autoremove"

# Disable prompt during package configuration
ENV DEBIAN_FRONTEND noninteractive

# Enable debugging in WebKit's sandbox.
ENV WEBKIT_ENABLE_DEBUG_PERMISSIONS_IN_SANDBOX "1"

# Used in webkitdirs.pm to prefer building against system libraries instead of the Flatpak SDK.
ENV WEBKIT_BUILD_USE_SYSTEM_LIBRARIES "1"

# Delete the default ubuntu user which has a UID of 1000.
# Podman refuses to map a user from the host if the UID is already in /etc/passwd.
RUN userdel ubuntu

# NOTE: All RUN commands contain the (autoremove / clean / rm step to ensure that no intermediate layer
#       ever contains unncessary stuff that never appears in the final image, only in deeper layers, and
#       thus increases the whole image size no gain, except an "easier to read" Dockerfile.

# Disable sandboxing (dropping privileges to _apt user during apt-get update/install/... fails when using
# podman in podman if both are rootless; since it's no gain in security in the container anyhow, disable it.
RUN echo 'APT::Sandbox::User "root";' > /etc/apt/apt.conf.d/no-sandbox

# Update package list, upgrade to latest version, install necessary packages for
# early bootstrapping: .deb package configuration + locale generation.
RUN ${APT_UPDATE} && \
    ${APT_INSTALL} apt-utils dialog libterm-readline-gnu-perl locales unminimize && \
    ${APT_UPGRADE} && ${APT_AUTOREMOVE}

# Disable exclusion of locales / translations / documentation (default in Ubuntu images)
RUN yes | /usr/bin/unminimize

# Switch to fixed locale.
RUN locale-gen ${CONTAINER_LOCALE}
ENV LC_ALL ${CONTAINER_LOCALE}
ENV LANG ${CONTAINER_LOCALE}
RUN dpkg-reconfigure locales

# Install all dependencies for WebKit/GStreamer/etc in one pass.
WORKDIR /var/tmp/wkdev-packages
COPY /required_system_packages/*.lst .

# We unconditionally install the GCC-based cross toolchain for armhf.
COPY /cross .

RUN sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources && \
    if [ "$(uname -m)" = "x86_64" ]; then \
        sed -r 's@(archive|security).ubuntu.com/ubuntu@ports.ubuntu.com/ubuntu-ports@g' </etc/apt/sources.list.d/ubuntu.sources >/etc/apt/sources.list.d/ubuntu-armhf.sources; \
        sed -i -r 's/^(Components:.*)/\1\nArchitectures: amd64/' /etc/apt/sources.list.d/ubuntu.sources; \
        sed -i -r 's/^(Components:.*)/\1\nArchitectures: armhf/' /etc/apt/sources.list.d/ubuntu-armhf.sources; \
    fi && \
    dpkg --add-architecture armhf && \
    ${APT_UPDATE} && \
    export LST_FILES=*.lst && \
    if [ "$(uname -m)" = "x86_64" -o "$(uname -m)" = "aarch64" ]; then export LST_FILES="$LST_FILES $(echo armhf/*.lst)"; fi; \
    for list in $LST_FILES; do \
        ${APT_INSTALL} $(sed -e "s/.*#.*//; /^$/d" "${list}" | tr '\n' ' '); \
    done; \
    ${APT_BUILDDEP} gst-libav1.0 gst-plugins-bad1.0 gst-plugins-base1.0 \
	                gst-plugins-good1.0 gst-plugins-ugly1.0 && \
    git clone --filter=blob:none --no-checkout --depth=1 https://github.com/WebKit/WebKit.git && \
    cd WebKit && \
    git sparse-checkout set Tools/ && \
    git checkout main && \
    yes | ./Tools/gtk/install-dependencies && \
    yes | ./Tools/wpe/install-dependencies && \
    cd .. && \
    rm -rf WebKit && \
    ${APT_AUTOREMOVE}

# GStreamer 1.26.x requires at least Meson 1.4. Install the latest version.
RUN pip install meson==1.8.2 --break-system-packages

# Ensure a strong TLS connection is always used when downloading sensitive files.
ARG CURL_DOWNLOAD="curl --proto =https --tlsv1.2 --show-error --silent --fail"

# Add LLVM repo for newer tooling, nothing is installed from it by default.
COPY /rootfs/etc/apt/sources.list.d/llvm.list /etc/apt/sources.list.d/llvm.list
RUN ${CURL_DOWNLOAD} https://apt.llvm.org/llvm-snapshot.gpg.key -o /etc/apt/trusted.gpg.d/apt.llvm.org.asc

# Add Rust environment.
ENV RUSTUP_HOME="/opt/rust" \
    CARGO_HOME="/opt/rust" \
    PATH="/opt/rust/bin:${PATH}"

RUN ${CURL_DOWNLOAD} https://sh.rustup.rs | sh -s -- -y && \
    rustup default 1.84.1 && \
    rustup component remove rust-docs && \
    cargo install --root /usr/local --version 0.9.1 --locked sccache && \
    cargo install --root /usr/local --version 0.10.9 --locked cargo-c

RUN git clone https://github.com/ystreet/librice.git && \
    cd librice && \
    git checkout 43980fa0041877bd8c9dbb7cc0b1e03613b98a80 && \
    cargo cinstall -p rice-proto --release --prefix=/usr --libdir=lib/$(gcc -dumpmachine) --library-type=cdylib && \
    cargo cinstall -p rice-io --release --prefix=/usr --libdir=lib/$(gcc -dumpmachine) --library-type=cdylib && \
    cd .. && \
    rm -fr librice

# Copy jhbuild helper files and do the initial build & install
COPY /jhbuild/jhbuildrc /etc/xdg/jhbuildrc
COPY /jhbuild/webkit-sdk-deps.modules /jhbuild/webkit-sdk-deps.modules
COPY /jhbuild/patches/ /jhbuild/patches/

WORKDIR /jhbuild
RUN git clone https://gitlab.gnome.org/GNOME/jhbuild.git && \
    cd jhbuild && \
    ./autogen.sh --prefix=/usr/local && \
    make && \
    make install && \
    export JHBUILD_RUN_AS_ROOT=1 WKDEV_IN_IMAGE_BUILD=1 && \
    jhbuild --exit-on-error --no-interact build && \
    rm -r /var/tmp/jhbuild

# Register basic JHBuild environment
# TODO: Instead of hardcoding here the values it would be better to
# explore the possibility of generating it dynamically with "jhbuild shell"
# when the user enters into the container (or similar), but that may cause
# issues with the env not exported when someone enter into the
# container via direct command exec rather than by login
ENV LIB "/jhbuild/install/lib"
ENV INCLUDE "/jhbuild/install/include"
ENV LD_LIBRARY_PATH "/jhbuild/install/lib"
ENV GST_PLUGIN_PATH_1_0 "/jhbuild/install/lib/gstreamer-1.0"
ENV PKG_CONFIG_PATH "/jhbuild/install/lib/pkgconfig:/jhbuild/install/share/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig"
ENV LDFLAGS "-L/jhbuild/install/lib"
ENV C_INCLUDE_PATH "/jhbuild/install/include"
ENV CPLUS_INCLUDE_PATH "/jhbuild/install/include"
ENV GI_TYPELIB_PATH "/jhbuild/install/lib/girepository-1.0"
ENV XDG_DATA_DIRS "/jhbuild/install/share:/usr/local/share:/usr/share"
ENV PATH "/jhbuild/install/bin:$PATH"

# Podman proxy, connecting to host instance
COPY /rootfs/usr/bin/podman-host /usr/bin/podman-host

COPY /rootfs/etc/ccache.conf /etc/ccache.conf

# Convenience symlinks for clang tools, the VSCode extension doesn't find these by default.
# FIXME: Reduce code duplication with `wkdev-set-default-clang`.
RUN bash -c 'for binary in /usr/bin/*-18; do \
        binary_name="$(basename $binary)"; \
        ln -s "${binary}" "/usr/local/bin/${binary_name::-3}"; \
    done'

# Fix Qt6 system packages - missing symlinks in the Ubuntu-provided packages.
RUN export QT_VERSION=$(qmake6 -query QT_VERSION) && \
    for directory in /usr/include/x86_64-linux-gnu/qt6/*; do \
      ln -s ${directory} ${directory}/${QT_VERSION}  >/dev/null 2>&1 || true; \
    done

# Check GStreamer plugins are installed.
RUN gst-inspect-1.0 audiornnoise && \
    gst-inspect-1.0 cea608tott && \
    gst-inspect-1.0 dav1ddec && \
    gst-inspect-1.0 isofmp4mux && \
    gst-inspect-1.0 rsrtp && \
    gst-inspect-1.0 x264enc && \
    gst-inspect-1.0 x265enc

# Check locally installed libraries.
RUN pkg-config --modversion rice-io && \
    pkg-config --modversion rice-proto

# Place the toolchainfiles in a discoverable location.
RUN mkdir -p /usr/share/wkdev-sdk/cross/armhf && cp -r /var/tmp/wkdev-packages/armhf/*.cmake /usr/share/wkdev-sdk/cross/armhf/

# Remove systemd services that would startup by default, when spawning
# systemd as PID 1 within the container (usually, we don't spawn systemd
# within the wkdev-sdk container, for interactive usage, but we do so
# when deploying the wkdev-sdk image as bot).
RUN find /etc/systemd/ -type l -name '*.service' -print -exec rm {} \;

# Switch back to interactive prompt, when using apt.
ENV DEBIAN_FRONTEND dialog
