FROM ubuntu:23.04

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get --assume-yes update && apt-get --assume-yes install sudo debian-keyring fuse-overlayfs gettext-base podman kmod tzdata && \
    apt-get --assume-yes clean && rm -rf /var/lib/apt/lists/* && \
    unset DEBIAN_FRONTEND