#!/usr/bin/env bash
# Copyright 2024 Igalia S.L.
# SPDX-License: MIT

if [ -f "${WKDEV_SDK}/.wkdev-sdk-root" ]; then
    source "${WKDEV_SDK}/utilities/application.sh"
else
    echo "Please set \${WKDEV_SDK} to point to the root of the wkdev-sdk checkout."
    exit 1
fi

min_clang_version=14
max_clang_version=22

init_application "${0}" "Installs and creates symlinks to set default clang executables" container-only

argsparse_use_option "=version:" "The clang version between ${min_clang_version}-${max_clang_version}" "type:uint"
argsparse_use_option "install-only" "Only install clang packages, do not create symlinks to set as default"
argsparse_use_option "latest" "Automatically install the latest available clang version"

argsparse_usage_description="$(cat <<EOF
<< Purpose >>

    Provides an easy way to install and switch between clang toolchains.

<< Examples >>

    $ ${application_name} --version=17
    $ ${application_name} --latest
EOF
)"

run() {

    argsparse_parse_options "${@}"

    _log_ ""

    local version
    if argsparse_is_option_set "latest"; then
        version="${max_clang_version}"
    elif argsparse_is_option_set "version"; then
        version="${program_options["version"]}"
        # Sanity check versions Ubuntu actually has.
        if (( ${version} < ${min_clang_version} )) || (( ${version} > ${max_clang_version})); then
            _log_ "${version} is not a valid value (between ${min_clang_version}-${max_clang_version})."
            exit 1
        fi
    else
        _log_ "Either --version or --latest must be specified."
        exit 1
    fi

    if [ ! -f "/usr/bin/clang-${version}" ]; then
        _log_ "Installing clang toolchain version ${version}"
        _log_ ""
        if ! sudo apt-get install "clang-tools-${version}" "clangd-${version}" "clang-format-${version}" "clang-tidy-${version}" "lld-${version}" "lldb-${version}" "llvm-${version}"; then
            _log_ ""
            _log_ "Failed to install clang toolchain"
            exit 1
        fi
    fi

    if argsparse_is_option_set "install-only"; then
        _log_ "Skipping symlink creation (--install-only specified)"
        exit 0
    fi

    local output_path
    if [ "$EUID" -eq 0 ]; then
        output_path="/usr/local/bin"
    else
        output_path="${HOME}/.local/bin"
    fi
    _log_ "Creating symlinks in ${output_path}"
    "${WKDEV_SDK}/scripts/helpers/create-clang-symlinks" "${version}" "${output_path}"
}

run "${@}"
