#!/usr/bin/env bash

if [ -f "${WKDEV_SDK}/.wkdev-sdk-root" ]; then
    source "${WKDEV_SDK}/utilities/application.sh"
else
    echo "Please set \${WKDEV_SDK} to point to the root of the wkdev-sdk checkout."
    exit 1
fi
source "${WKDEV_SDK}/utilities/prerequisites.sh"

init_application "${0}" "Configures Visual Studio Code." container-only

verify_executables_exist curl

argsparse_allow_no_argument true
argsparse_use_option "=yes" "Assume yes for all prompts."

install_vscode() {

    echo ""
    echo "Installing Visual Studio Code..."
    echo ""

    if which code > /dev/null; then
        echo "Visual Studio Code is already installed."
        return
    fi

    if ! curl --silent --fail --location "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64" -o /tmp/code.deb; then
        echo "Failed to download Visual Studio Code."
        exit 1
    fi

    if ! sudo apt install /tmp/code.deb; then
        echo "Failed to install Visual Studio Code."
        rm /tmp/code.deb
        exit 1
    fi

    rm /tmp/code.deb
    echo ""
    echo "Visual Studio Code has been installed."
}

install_extension() {

    local extension_name="${1}"
    local description="${2}"
    local ask="${3:-false}"
    local response
    local installed_extensions

    readarray installed_extensions < <(code --list-extensions)

    if [[ "${installed_extensions[*]}" =~ "${extension_name}" ]]; then
        echo "VSCode extension already installed: ${extension_name}"
        return
    fi

    if [ "${ask}" = true ] && ! argsparse_is_option_set "yes"; then
        read -r -p "Install VSCode extension: ${extension_name} (${description})? [Y/n] " response
        if [[ "$response" =~ ^([nN][oO]|[nN])$ ]]; then
            return
        fi
    else
        echo "Installing VSCode extension: ${extension_name} (${description})..."
    fi

    if ! code --install-extension "${extension_name}" &>/dev/null; then
        echo "Failed to install VSCode extension: ${extension_name}"
        exit 1
    fi

    echo "Installed"
    echo ""
}

install_extensions() {

    echo ""
    echo "Installing extensions..."
    echo ""
    install_extension ms-vscode.cmake-tools "CMake support"
    install_extension llvm-vs-code-extensions.vscode-clangd "C/C++ support"
    install_extension mads-hartmann.bash-ide-vscode "BASH support" true
    install_extension ms-python.python "Python support" true
}

run() {

    argsparse_parse_options "${@}"

    install_vscode
    install_extensions
}

run "${@}"
