#!/usr/bin/env bash
# Copyright 2024 Igalia S.L.
# SPDX-License: MIT

[ -f "${WKDEV_SDK}/.wkdev-sdk-root" ] && source "${WKDEV_SDK}/utilities/application.sh" || { echo "Please set \${WKDEV_SDK} to point to the root of the wkdev-sdk checkout."; exit 1; }
init_application "${0}" "" container-only

argsparse_use_option trace "Enable 'xtrace' mode for this script"

# Source utility script fragments
source "${WKDEV_SDK}/utilities/ansi-code-generator/ansi.sh"

argsparse_usage_description="$(cat <<EOF
<< Purpose >>

    Shows the welcome message upon container login.

<< Examples >>

    $ ${application_name}
EOF
)"

process_command_line_arguments() {

    # Allow empty command line
    argsparse_allow_no_argument yes

    argsparse_parse_options "${@}"
    argsparse_is_option_set "trace" && set -o xtrace
}

# Runs a single test.
run_test() {

    local description="${1}"
    local command="${2}"
    shift 2


    _log_ ""
    _log_ "-> ${description}:"
    "${command}" "${@}"
}

# Main functionality
run() {

    process_command_line_arguments "${@}"

    pushd "${WKDEV_SDK}" &>/dev/null

    _log_ ""
    _log_ '          _        ______   _______                  _______  ______   _       '
    _log_ '|\     /|| \    /\(  __  \ (  ____ \|\     /|       (  ____ \(  __  \ | \    /\'
    _log_ '| )   ( ||  \  / /| (  \  )| (    \/| )   ( |       | (    \/| (  \  )|  \  / /'
    _log_ '| | _ | ||  (_/ / | |   ) || (__    | |   | | _____ | (_____ | |   ) ||  (_/ / '
    _log_ '| |( )| ||   _ (  | |   | ||  __)   ( (   ) )(_____)(_____  )| |   | ||   _ (  '
    _log_ '| || || ||  ( \ \ | |   ) || (       \ \_/ /              ) || |   ) ||  ( \ \ '
    _log_ '| () () ||  /  \ \| (__/  )| (____/\  \   /         /\____) || (__/  )|  /  \ \'
    _log_ '(_______)|_/    \/(______/ (_______/   \_/          \_______)(______/ |_/    \/'
    _log_ ""
    _log_ ""
    _log_ "Git repository 'wkdev-sdk' ($(ansi::bold) $(git branch --show-current) @ $(git rev-parse HEAD) $(ansi::normal))"
    _log_ " 🠲  Last commit: $(ansi::bold)$(git log -1 --format=%cd)$(ansi::normal)"
    _log_ ""
    _log_ "NOTE:"
    _log_ " - Be sure to try $(ansi::bold)\`wkdev-test-host-integration\`$(ansi::normal) to verify your container setup behaves as expected."
    _log_ ""
    _log_ " - The home directory $(ansi::bold)\${HOME}$(ansi::normal)=${HOME} within the container is $(ansi::underline)$(ansi::bold)not the same$(ansi::normal)$(ansi::noUnderline) as your host home directory."
    _log_ "   You can find your regular host home directory in the container under $(ansi::bold)\${HOST_HOME}$(ansi::normal)=${HOST_HOME}."
    _log_ ""
    _log_ " - Instructions on how to build / debug / profile WebKit can be found in the SDK documentation, either"
    _log_ "   locally in $(ansi::underline)\${WKDEV_SDK}/docs$(ansi::noUnderline) or online $(ansi::underline)https://github.com/Igalia/wkdev-sdk/tree/main/docs$(ansi::noUnderline)".
    _log_ ""
    _log_ " - WebKit builds and tests will happen on a common directory at $(ansi::bold)/sdk/webkit$(ansi::normal) when using the SDK."
    _log_ "   This allows relocating the build directory and executing tests anywhere without rebuilding,"
    _log_ "   and also sharing ccache/sccache artifacts across directories and between bots and developers."
    _log_ "   To connect with the remote ccache service used by the bots, run $(ansi::bold)\`wkdev-setup-remote-ccache\`$(ansi::normal)."
    _log_ "   To opt out of common-directory builds at /sdk/webkit, export the following environment variable"
    _log_ "   in the container's \${HOME}/.bashrc or equivalent: WEBKIT_CONTAINER_SDK_INSIDE_MOUNT_NAMESPACE=1"

    popd &>/dev/null
}

run "${@}"
