#!/usr/bin/env bash

source "${WKDEV_SDK}/utilities/application.sh" || { echo "Please set \${WKDEV_SDK} to point to the root of the wkdev-sdk checkout."; exit 1; }
init_application "${0}" "" container-only

argsparse_allow_no_argument true
argsparse_use_option trace        "Enable 'xtrace' mode for this script"

argsparse_usage_description="$(cat <<EOF
<< Purpose >>

    ${application_name} is ran on enter for every wkdev-sdk container.

    It takes information from your host environment and ensures that the container
    contains all host state such as the WAYLAND_DISPLAY in use.

    NOTE: You do NOT need to call this script manually, it is automatically used during container startup.
EOF
)"

process_command_line_arguments() {

    argsparse_parse_options "${@}"
    argsparse_is_option_set "trace" && set -o xtrace
}

try_mount_host_wayland() {
    local host_wayland_socket="/host/run/${WAYLAND_DISPLAY}"
    local container_wayland_socket="${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}"

    if [ -L "${container_wayland_socket}" ]; then
        # Silently succeed.
        return
    elif [ -S "${host_wayland_socket}" ]; then
        echo ""
        echo "-> Mounting host Wayland socket (${WAYLAND_DISPLAY})."
        ln -s "${host_wayland_socket}" "${container_wayland_socket}"
    else
        echo ""
        echo "-> Skipping host Wayland socket (${WAYLAND_DISPLAY}) - not found."
    fi

    if [[ ! -f "${container_wayland_socket}.lock" &&  -f "${host_wayland_socket}.lock" ]]; then
        ln -s "${host_wayland_socket}.lock" "${container_wayland_socket}.lock"
    fi

    echo ""
}

# Main functionality
run() {

    process_command_line_arguments "${@}"

    XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR-"/run/user/$(id --user)"}
    WAYLAND_DISPLAY=${WAYLAND_DISPLAY-"wayland-0"}

    try_mount_host_wayland
}

run "${@}"
