#!/usr/bin/env bash
# Copyright 2024 Igalia S.L.
# SPDX-License: MIT

[ -f "${WKDEV_SDK}/.wkdev-sdk-root" ] && source "${WKDEV_SDK}/utilities/application.sh" || { echo "Please set \${WKDEV_SDK} to point to the root of the wkdev-sdk checkout."; exit 1; }
init_application "${0}" "Modify 'perf' related host kernel parameters to enable CPU profiling for unprivileged users." host-and-container

# Source utility script fragments
source "${WKDEV_SDK}/utilities/cpu-profiling.sh"

argsparse_use_option trace "Enable 'xtrace' mode for this script"

argsparse_usage_description="$(cat <<EOF
<< Purpose >>

$(get_perf_settings_help_message)

    \`${application_name}\` remembers the current setting, and switches to '$(get_desired_perf_event_kernel_setting_value_for_profiling)'. Use \`wkdev-stop-profiling\`, the
    companion tool, to restore the original 'kernel.$(get_perf_event_kernel_setting)' setting. Both tools will ask for superuser privileges.
EOF
)"

process_command_line_arguments() {

    # Allow empty command line
    argsparse_allow_no_argument yes

    argsparse_parse_options "${@}"
    argsparse_is_option_set "trace" && set -o xtrace
}

# Main functionality
run() {

    process_command_line_arguments "${@}"
    enable_perf_settings_for_cpu_profiling
}

run "${@}"
