#!/usr/bin/env bash
# Copyright 2024 Igalia S.L.
# SPDX-License: MIT

[ -f "${WKDEV_SDK}/.wkdev-sdk-root" ] && source "${WKDEV_SDK}/utilities/application.sh" || { echo "Please set \${WKDEV_SDK} to point to the root of the wkdev-sdk checkout."; exit 1; }
init_application "${0}" "Launcher for wkdev commands" host-and-container

usage() {
    echo "${application_name} COMMAND [ARGS...]"
    echo ""
    echo "These are common wkdev commands used in various situations:"
    wkdev_generic_commands
    echo ""
    echo "These are wkdev commands intended for execution on the host system:"
    wkdev_host_commands
    echo ""
    echo "These are wkdev commands intended for execution on the container:"
    wkdev_container_commands
}

wkdev_generic_commands() {
    for item in "${application_directory}"/wkdev-* ; do
        [[ -x $item ]] || continue
        echo "  - ${item##*/}"
    done
}

wkdev_host_commands() {
    for item in "${application_directory}"/host-only/wkdev-* ; do
        [[ -x $item ]] || continue
        echo "  - ${item##*/}"
    done
}

wkdev_container_commands() {
    for item in "${application_directory}"/container-only/wkdev-* ; do
        [[ -x $item ]] || continue
        echo "  - ${item##*/}"
    done
}

find_wkdev_command() {
    local command="${1}"

    for item in "${application_directory}"/wkdev-* \
                "${application_directory}"/host-only/wkdev-* \
                "${application_directory}"/container-only/wkdev-*
    do
        [[ -x $item ]] || continue

        if [[ ${item##*/wkdev-} = $command ]] ; then
            echo "$item"
            return
        fi
    done

    return 1
}

# Main.
if [[ ${#} -eq 0 ]]; then
    usage 1>&2
    exit 1
fi

if [[ $1 = help || $1 = -h || $1 = --help ]] ; then
	usage
	exit
fi

COMMAND="${1}"
shift

# Find command in list of all available wkdev- commands.
COMMAND=$(find_wkdev_command "${COMMAND}")

# Execute command.
if [[ -x "${COMMAND}" ]]; then
    ${COMMAND} ${@}
fi

