#!/usr/bin/env bash
# Copyright 2024 Igalia S.L.
# SPDX-License: MIT

[ -f "${WKDEV_SDK}/.wkdev-sdk-root" ] && source "${WKDEV_SDK}/utilities/application.sh" || { echo "Please set \${WKDEV_SDK} to point to the root of the wkdev-sdk checkout."; exit 1; }
init_application "${0}" "Launcher for wkdev commands" host-and-container

usage() {
    echo "${application_name} COMMAND [ARGS...]"
    echo ""
    echo "These are common wkdev commands used in various situations:"
    wkdev_generic_commands
    echo ""
    echo "These are wkdev commands intended for execution on the host system:"
    wkdev_host_commands
    echo ""
    echo "These are wkdev commands intended for execution on the container:"
    wkdev_container_commands
}

wkdev_generic_commands() {
    for item in "${application_directory}"/wkdev-* ; do
        [[ -x $item ]] || continue
        echo "  - ${item##*/}"
    done
}

wkdev_host_commands() {
    for item in "${application_directory}"/host-only/wkdev-* ; do
        [[ -x $item ]] || continue
        echo "  - ${item##*/}"
    done
}

wkdev_container_commands() {
    for item in "${application_directory}"/container-only/wkdev-* ; do
        [[ -x $item ]] || continue
        echo "  - ${item##*/}"
    done
}

# Main.
if [[ ${#} -eq 0 ]]; then
    usage 1>&2
    exit 1
fi

if [[ $1 = help || $1 = -h || $1 = --help ]] ; then
	usage
	exit
fi

for path in "${application_directory}"/{,host-only/,container-only/}"wkdev-$1" ; do
	if [[ -x $path ]] ; then
		shift
		exec "$path" "$@"
	fi
done

echo "${0##*/}: No such subcommand: $1." 1>&2
echo "Hint: Use '${0##*/} help' for a list." 1>&2
exit 1
